package a.dev.mobile_thread.models

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "Tr")
data class Tr(
    @PrimaryKey
    @ColumnInfo(name = "_id") val _id: Int,


    @ColumnInfo(name = "nominal_diameter") val nominal_diameter: String?,

    @ColumnInfo(name = "pitch") val pitch: String?,
    @ColumnInfo(name = "D4") val D4: String?,
    @ColumnInfo(name = "d2_D2") val d2_D2: String?,
    @ColumnInfo(name = "d3") val d3: String?,
    @ColumnInfo(name = "D1") val D1: String?,
    @ColumnInfo(name = "es_d_6e") val es_d_6e: String?,
    @ColumnInfo(name = "ei_d_6e") val ei_d_6e: String?,
    @ColumnInfo(name = "es_d2_6e") val es_d2_6e: String?,
    @ColumnInfo(name = "ei_d2_6e") val ei_d2_6e: String?,
    @ColumnInfo(name = "es_d3_6e") val es_d3_6e: String?,
    @ColumnInfo(name = "ei_d3_6e") val ei_d3_6e: String?,
    @ColumnInfo(name = "es_d_6g") val es_d_6g: String?,
    @ColumnInfo(name = "ei_d_6g") val ei_d_6g: String?,
    @ColumnInfo(name = "es_d2_6g") val es_d2_6g: String?,
    @ColumnInfo(name = "ei_d2_6g") val ei_d2_6g: String?,
    @ColumnInfo(name = "es_d3_6g") val es_d3_6g: String?,
    @ColumnInfo(name = "ei_d3_6g") val ei_d3_6g: String?,
    @ColumnInfo(name = "es_d_7e") val es_d_7e: String?,
    @ColumnInfo(name = "ei_d_7e") val ei_d_7e: String?,
    @ColumnInfo(name = "es_d2_7e") val es_d2_7e: String?,
    @ColumnInfo(name = "ei_d2_7e") val ei_d2_7e: String?,
    @ColumnInfo(name = "es_d3_7e") val es_d3_7e: String?,
    @ColumnInfo(name = "ei_d3_7e") val ei_d3_7e: String?,
    @ColumnInfo(name = "es_d_7g") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ei_d_7g") val nominal_diameter_1: String?,
    @ColumnInfo(name = "es_d2_7g") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ei_d2_7g") val nominal_diameter_1: String?,
    @ColumnInfo(name = "es_d3_7g") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ei_d3_7g") val nominal_diameter_1: String?,
    @ColumnInfo(name = "es_d_8c") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ei_d_8c") val nominal_diameter_1: String?,
    @ColumnInfo(name = "es_d2_8c") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ei_d2_8c") val nominal_diameter_1: String?,
    @ColumnInfo(name = "es_d3_8c") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ei_d3_8c") val nominal_diameter_1: String?,
    @ColumnInfo(name = "es_d_8e") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ei_d_8e") val nominal_diameter_1: String?,
    @ColumnInfo(name = "es_d2_8e") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ei_d2_8e") val nominal_diameter_1: String?,
    @ColumnInfo(name = "es_d3_8e") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ei_d3_8e") val nominal_diameter_1: String?,
    @ColumnInfo(name = "es_d_9c") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ei_d_9c") val nominal_diameter_1: String?,
    @ColumnInfo(name = "es_d2_9c") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ei_d2_9c") val nominal_diameter_1: String?,
    @ColumnInfo(name = "es_d3_9c") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ei_d3_9c") val nominal_diameter_1: String?,
    @ColumnInfo(name = "EI_D4_6H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ES_D2_6H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "EI_D2_6H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ES_D1_6H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "EI_D1_6H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "EI_D4_7H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ES_D2_7H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "EI_D2_7H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ES_D1_7H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "EI_D1_7H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "EI_D4_8H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ES_D2_8H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "EI_D2_8H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ES_D1_8H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "EI_D1_8H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "EI_D4_9H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ES_D2_9H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "EI_D2_9H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "ES_D1_9H_1") val nominal_diameter_1: String?,
    @ColumnInfo(name = "EI_D1_9H_1") val nominal_diameter_1: String?,


    )
